<?php

return [

/* ---------------- EASY (20) ---------------- */

["id"=>1,"difficulty"=>"easy","q"=>"2 + 2?","options"=>["A"=>"3","B"=>"4","C"=>"5","D"=>"6"],"answer"=>"B"],
["id"=>2,"difficulty"=>"easy","q"=>"Capital of France?","options"=>["A"=>"Paris","B"=>"Rome","C"=>"Berlin","D"=>"Madrid"],"answer"=>"A"],
["id"=>3,"difficulty"=>"easy","q"=>"What color is the sky?","options"=>["A"=>"Blue","B"=>"Green","C"=>"Red","D"=>"Yellow"],"answer"=>"A"],
["id"=>4,"difficulty"=>"easy","q"=>"5 x 3?","options"=>["A"=>"8","B"=>"15","C"=>"10","D"=>"20"],"answer"=>"B"],
["id"=>5,"difficulty"=>"easy","q"=>"Which is a fruit?","options"=>["A"=>"Carrot","B"=>"Potato","C"=>"Apple","D"=>"Onion"],"answer"=>"C"],
["id"=>6,"difficulty"=>"easy","q"=>"Water freezes at?","options"=>["A"=>"0°C","B"=>"100°C","C"=>"50°C","D"=>"10°C"],"answer"=>"A"],
["id"=>7,"difficulty"=>"easy","q"=>"Sun rises in the?","options"=>["A"=>"West","B"=>"North","C"=>"East","D"=>"South"],"answer"=>"C"],
["id"=>8,"difficulty"=>"easy","q"=>"Which is a mammal?","options"=>["A"=>"Shark","B"=>"Dolphin","C"=>"Snake","D"=>"Frog"],"answer"=>"B"],
["id"=>9,"difficulty"=>"easy","q"=>"HTML is used for?","options"=>["A"=>"Styling","B"=>"Structure","C"=>"Database","D"=>"Server"],"answer"=>"B"],
["id"=>10,"difficulty"=>"easy","q"=>"10 / 2?","options"=>["A"=>"2","B"=>"3","C"=>"5","D"=>"8"],"answer"=>"C"],
["id"=>11,"difficulty"=>"easy","q"=>"Primary color?","options"=>["A"=>"Green","B"=>"Purple","C"=>"Red","D"=>"Pink"],"answer"=>"C"],
["id"=>12,"difficulty"=>"easy","q"=>"Which is a planet?","options"=>["A"=>"Moon","B"=>"Mars","C"=>"Sun","D"=>"Star"],"answer"=>"B"],
["id"=>13,"difficulty"=>"easy","q"=>"CSS is used for?","options"=>["A"=>"Logic","B"=>"Structure","C"=>"Styling","D"=>"Database"],"answer"=>"C"],
["id"=>14,"difficulty"=>"easy","q"=>"Which is a browser?","options"=>["A"=>"Chrome","B"=>"Python","C"=>"Linux","D"=>"SQL"],"answer"=>"A"],
["id"=>15,"difficulty"=>"easy","q"=>"3 + 7?","options"=>["A"=>"9","B"=>"10","C"=>"11","D"=>"12"],"answer"=>"B"],
["id"=>16,"difficulty"=>"easy","q"=>"Which is a vegetable?","options"=>["A"=>"Banana","B"=>"Carrot","C"=>"Apple","D"=>"Grape"],"answer"=>"B"],
["id"=>17,"difficulty"=>"easy","q"=>"Which is a color?","options"=>["A"=>"Dog","B"=>"Blue","C"=>"Run","D"=>"Jump"],"answer"=>"B"],
["id"=>18,"difficulty"=>"easy","q"=>"What is 1+1?","options"=>["A"=>"1","B"=>"2","C"=>"3","D"=>"4"],"answer"=>"B"],
["id"=>19,"difficulty"=>"easy","q"=>"Which is a shape?","options"=>["A"=>"Circle","B"=>"Run","C"=>"Jump","D"=>"Eat"],"answer"=>"A"],
["id"=>20,"difficulty"=>"easy","q"=>"Which is an animal?","options"=>["A"=>"Table","B"=>"Dog","C"=>"Chair","D"=>"Car"],"answer"=>"B"],

/* ---------------- MEDIUM (15) ---------------- */

["id"=>21,"difficulty"=>"medium","q"=>"Capital of Germany?","options"=>["A"=>"Berlin","B"=>"Paris","C"=>"Rome","D"=>"Madrid"],"answer"=>"A"],
["id"=>22,"difficulty"=>"medium","q"=>"HTML stands for?","options"=>["A"=>"Hyper Text Markup Language","B"=>"High Text Machine","C"=>"Hyper Tool","D"=>"None"],"answer"=>"A"],
["id"=>23,"difficulty"=>"medium","q"=>"Binary of 2?","options"=>["A"=>"10","B"=>"01","C"=>"11","D"=>"00"],"answer"=>"A"],
["id"=>24,"difficulty"=>"medium","q"=>"Which is backend?","options"=>["A"=>"HTML","B"=>"CSS","C"=>"PHP","D"=>"Bootstrap"],"answer"=>"C"],
["id"=>25,"difficulty"=>"medium","q"=>"SQL is used for?","options"=>["A"=>"Styling","B"=>"Database","C"=>"Frontend","D"=>"Animation"],"answer"=>"B"],
["id"=>26,"difficulty"=>"medium","q"=>"Largest ocean?","options"=>["A"=>"Atlantic","B"=>"Indian","C"=>"Pacific","D"=>"Arctic"],"answer"=>"C"],
["id"=>27,"difficulty"=>"medium","q"=>"Speed of light approx?","options"=>["A"=>"300k km/s","B"=>"150k","C"=>"1M","D"=>"10k"],"answer"=>"A"],
["id"=>28,"difficulty"=>"medium","q"=>"Python is?","options"=>["A"=>"Snake","B"=>"Language","C"=>"Game","D"=>"Browser"],"answer"=>"B"],
["id"=>29,"difficulty"=>"medium","q"=>"Which is OS?","options"=>["A"=>"Windows","B"=>"Chrome","C"=>"HTML","D"=>"CSS"],"answer"=>"A"],
["id"=>30,"difficulty"=>"medium","q"=>"RAM is?","options"=>["A"=>"Storage","B"=>"Memory","C"=>"CPU","D"=>"GPU"],"answer"=>"B"],
["id"=>31,"difficulty"=>"medium","q"=>"Git is used for?","options"=>["A"=>"Design","B"=>"Version control","C"=>"Database","D"=>"Hosting"],"answer"=>"B"],
["id"=>32,"difficulty"=>"medium","q"=>"IPv4 length?","options"=>["A"=>"32 bits","B"=>"64 bits","C"=>"128 bits","D"=>"16 bits"],"answer"=>"A"],
["id"=>33,"difficulty"=>"medium","q"=>"Which is NOT a browser?","options"=>["A"=>"Chrome","B"=>"Firefox","C"=>"Safari","D"=>"Python"],"answer"=>"D"],
["id"=>34,"difficulty"=>"medium","q"=>"Which company made Windows?","options"=>["A"=>"Apple","B"=>"Google","C"=>"Microsoft","D"=>"Amazon"],"answer"=>"C"],
["id"=>35,"difficulty"=>"medium","q"=>"Which is frontend?","options"=>["A"=>"PHP","B"=>"HTML","C"=>"MySQL","D"=>"Node"],"answer"=>"B"],

/* ---------------- HARD (15) ---------------- */

["id"=>36,"difficulty"=>"hard","q"=>"CPU stands for?","options"=>["A"=>"Central Processing Unit","B"=>"Control Unit","C"=>"Computer Unit","D"=>"Core Unit"],"answer"=>"A"],
["id"=>37,"difficulty"=>"hard","q"=>"Time complexity of binary search?","options"=>["A"=>"O(n)","B"=>"O(log n)","C"=>"O(n^2)","D"=>"O(1)"],"answer"=>"B"],
["id"=>38,"difficulty"=>"hard","q"=>"Which is NOT language?","options"=>["A"=>"Python","B"=>"Java","C"=>"HTML","D"=>"C++"],"answer"=>"C"],
["id"=>39,"difficulty"=>"hard","q"=>"OSI layers?","options"=>["A"=>"5","B"=>"6","C"=>"7","D"=>"8"],"answer"=>"C"],
["id"=>40,"difficulty"=>"hard","q"=>"Hash table avg lookup?","options"=>["A"=>"O(n)","B"=>"O(log n)","C"=>"O(1)","D"=>"O(n^2)"],"answer"=>"C"],
["id"=>41,"difficulty"=>"hard","q"=>"DNS stands for?","options"=>["A"=>"Domain Name System","B"=>"Data Network System","C"=>"Digital Node System","D"=>"None"],"answer"=>"A"],
["id"=>42,"difficulty"=>"hard","q"=>"Recursion is?","options"=>["A"=>"Loop","B"=>"Function calling itself","C"=>"Variable","D"=>"Error"],"answer"=>"B"],
["id"=>43,"difficulty"=>"hard","q"=>"Big-O of quicksort avg?","options"=>["A"=>"O(n log n)","B"=>"O(n^2)","C"=>"O(n)","D"=>"O(log n)"],"answer"=>"A"],
["id"=>44,"difficulty"=>"hard","q"=>"Which protocol is secure?","options"=>["A"=>"HTTP","B"=>"HTTPS","C"=>"FTP","D"=>"SMTP"],"answer"=>"B"],
["id"=>45,"difficulty"=>"hard","q"=>"Which is a NoSQL DB?","options"=>["A"=>"MySQL","B"=>"MongoDB","C"=>"PostgreSQL","D"=>"Oracle"],"answer"=>"B"],
["id"=>46,"difficulty"=>"hard","q"=>"Stack follows?","options"=>["A"=>"FIFO","B"=>"LIFO","C"=>"Random","D"=>"None"],"answer"=>"B"],
["id"=>47,"difficulty"=>"hard","q"=>"Queue follows?","options"=>["A"=>"LIFO","B"=>"FIFO","C"=>"Random","D"=>"None"],"answer"=>"B"],
["id"=>48,"difficulty"=>"hard","q"=>"Which is not OOP pillar?","options"=>["A"=>"Encapsulation","B"=>"Inheritance","C"=>"Polymorphism","D"=>"Compilation"],"answer"=>"D"],
["id"=>49,"difficulty"=>"hard","q"=>"Which sorting is fastest avg?","options"=>["A"=>"Bubble","B"=>"Selection","C"=>"Quick","D"=>"Insertion"],"answer"=>"C"],
["id"=>50,"difficulty"=>"hard","q"=>"Which uses key-value pairs?","options"=>["A"=>"Array","B"=>"Stack","C"=>"HashMap","D"=>"Queue"],"answer"=>"C"],

/* ---------------- EASY (25) ---------------- */
["id"=>51,"difficulty"=>"easy","q"=>"What is 6 + 4?","options"=>["A"=>"9","B"=>"10","C"=>"11","D"=>"12"],"answer"=>"B"],
["id"=>52,"difficulty"=>"easy","q"=>"Color of grass?","options"=>["A"=>"Blue","B"=>"Green","C"=>"Red","D"=>"Black"],"answer"=>"B"],
["id"=>53,"difficulty"=>"easy","q"=>"Which is a programming language?","options"=>["A"=>"HTML","B"=>"Python","C"=>"CSS","D"=>"Photoshop"],"answer"=>"B"],
["id"=>54,"difficulty"=>"easy","q"=>"How many days in a week?","options"=>["A"=>"5","B"=>"6","C"=>"7","D"=>"8"],"answer"=>"C"],
["id"=>55,"difficulty"=>"easy","q"=>"Which is a pet animal?","options"=>["A"=>"Lion","B"=>"Tiger","C"=>"Dog","D"=>"Wolf"],"answer"=>"C"],
["id"=>56,"difficulty"=>"easy","q"=>"What is 9 - 3?","options"=>["A"=>"5","B"=>"6","C"=>"7","D"=>"8"],"answer"=>"B"],
["id"=>57,"difficulty"=>"easy","q"=>"Which is a fruit?","options"=>["A"=>"Tomato","B"=>"Potato","C"=>"Onion","D"=>"Carrot"],"answer"=>"A"],
["id"=>58,"difficulty"=>"easy","q"=>"Which is used to drink water?","options"=>["A"=>"Plate","B"=>"Cup","C"=>"Book","D"=>"Pen"],"answer"=>"B"],
["id"=>59,"difficulty"=>"easy","q"=>"Which planet do we live on?","options"=>["A"=>"Mars","B"=>"Earth","C"=>"Venus","D"=>"Jupiter"],"answer"=>"B"],
["id"=>60,"difficulty"=>"easy","q"=>"Which is a transport?","options"=>["A"=>"Car","B"=>"Tree","C"=>"Dog","D"=>"House"],"answer"=>"A"],
["id"=>61,"difficulty"=>"easy","q"=>"What is 2 x 2?","options"=>["A"=>"2","B"=>"3","C"=>"4","D"=>"5"],"answer"=>"C"],
["id"=>62,"difficulty"=>"easy","q"=>"Which is a drink?","options"=>["A"=>"Milk","B"=>"Bread","C"=>"Rice","D"=>"Meat"],"answer"=>"A"],
["id"=>63,"difficulty"=>"easy","q"=>"Which is a shape?","options"=>["A"=>"Square","B"=>"Run","C"=>"Jump","D"=>"Eat"],"answer"=>"A"],
["id"=>64,"difficulty"=>"easy","q"=>"Which is hot?","options"=>["A"=>"Ice","B"=>"Fire","C"=>"Snow","D"=>"Water"],"answer"=>"B"],
["id"=>65,"difficulty"=>"easy","q"=>"Which is a month?","options"=>["A"=>"Monday","B"=>"January","C"=>"Yesterday","D"=>"Today"],"answer"=>"B"],
["id"=>66,"difficulty"=>"easy","q"=>"Which is a color?","options"=>["A"=>"Blue","B"=>"Eat","C"=>"Run","D"=>"Sleep"],"answer"=>"A"],
["id"=>67,"difficulty"=>"easy","q"=>"Which is a vegetable?","options"=>["A"=>"Apple","B"=>"Carrot","C"=>"Banana","D"=>"Grape"],"answer"=>"B"],
["id"=>68,"difficulty"=>"easy","q"=>"What comes after 10?","options"=>["A"=>"11","B"=>"9","C"=>"12","D"=>"13"],"answer"=>"A"],
["id"=>69,"difficulty"=>"easy","q"=>"Which is used for writing?","options"=>["A"=>"Pen","B"=>"Cup","C"=>"Plate","D"=>"Shoe"],"answer"=>"A"],
["id"=>70,"difficulty"=>"easy","q"=>"Which is an animal?","options"=>["A"=>"Rock","B"=>"Dog","C"=>"Chair","D"=>"Table"],"answer"=>"B"],
["id"=>71,"difficulty"=>"easy","q"=>"Which is cold?","options"=>["A"=>"Fire","B"=>"Ice","C"=>"Sun","D"=>"Lava"],"answer"=>"B"],
["id"=>72,"difficulty"=>"easy","q"=>"Which is a fruit?","options"=>["A"=>"Apple","B"=>"Potato","C"=>"Carrot","D"=>"Onion"],"answer"=>"A"],
["id"=>73,"difficulty"=>"easy","q"=>"Which is a number?","options"=>["A"=>"Ten","B"=>"Blue","C"=>"Run","D"=>"Eat"],"answer"=>"A"],
["id"=>74,"difficulty"=>"easy","q"=>"Which is a tool?","options"=>["A"=>"Hammer","B"=>"Dog","C"=>"Car","D"=>"Tree"],"answer"=>"A"],
["id"=>75,"difficulty"=>"easy","q"=>"Which is used for sleep?","options"=>["A"=>"Bed","B"=>"Chair","C"=>"Table","D"=>"Cup"],"answer"=>"A"],

/* ---------------- MEDIUM (25) ---------------- */
["id"=>76,"difficulty"=>"medium","q"=>"What is 15 x 2?","options"=>["A"=>"25","B"=>"30","C"=>"35","D"=>"40"],"answer"=>"B"],
["id"=>77,"difficulty"=>"medium","q"=>"What does CPU do?","options"=>["A"=>"Stores data","B"=>"Processes data","C"=>"Displays images","D"=>"Prints files"],"answer"=>"B"],
["id"=>78,"difficulty"=>"medium","q"=>"Which is a scripting language?","options"=>["A"=>"HTML","B"=>"CSS","C"=>"JavaScript","D"=>"SQL"],"answer"=>"C"],
["id"=>79,"difficulty"=>"medium","q"=>"What is RAM used for?","options"=>["A"=>"Long storage","B"=>"Temporary memory","C"=>"Printing","D"=>"Internet"],"answer"=>"B"],
["id"=>80,"difficulty"=>"medium","q"=>"What does HTTP stand for?","options"=>["A"=>"HyperText Transfer Protocol","B"=>"High Text Transfer Program","C"=>"Hyper Tool Text Process","D"=>"None"],"answer"=>"A"],
["id"=>81,"difficulty"=>"medium","q"=>"Which is a database language?","options"=>["A"=>"HTML","B"=>"SQL","C"=>"CSS","D"=>"Python"],"answer"=>"B"],
["id"=>82,"difficulty"=>"medium","q"=>"Which is a framework?","options"=>["A"=>"Laravel","B"=>"Python","C"=>"HTML","D"=>"Linux"],"answer"=>"A"],
["id"=>83,"difficulty"=>"medium","q"=>"Which memory is volatile?","options"=>["A"=>"ROM","B"=>"RAM","C"=>"Disk","D"=>"SSD"],"answer"=>"B"],
["id"=>84,"difficulty"=>"medium","q"=>"What is output device?","options"=>["A"=>"Keyboard","B"=>"Mouse","C"=>"Monitor","D"=>"CPU"],"answer"=>"C"],
["id"=>85,"difficulty"=>"medium","q"=>"Which is a cloud service?","options"=>["A"=>"AWS","B"=>"HTML","C"=>"CSS","D"=>"RAM"],"answer"=>"A"],
["id"=>86,"difficulty"=>"medium","q"=>"What does URL stand for?","options"=>["A"=>"Uniform Resource Locator","B"=>"Universal Route Link","C"=>"User Resource Line","D"=>"None"],"answer"=>"A"],
["id"=>87,"difficulty"=>"medium","q"=>"Which is a backend language?","options"=>["A"=>"PHP","B"=>"HTML","C"=>"CSS","D"=>"Photoshop"],"answer"=>"A"],
["id"=>88,"difficulty"=>"medium","q"=>"What is binary 5?","options"=>["A"=>"101","B"=>"111","C"=>"100","D"=>"110"],"answer"=>"A"],
["id"=>89,"difficulty"=>"medium","q"=>"Which is a version control tool?","options"=>["A"=>"Git","B"=>"SQL","C"=>"HTML","D"=>"CSS"],"answer"=>"A"],
["id"=>90,"difficulty"=>"medium","q"=>"What is 10% of 200?","options"=>["A"=>"10","B"=>"20","C"=>"30","D"=>"40"],"answer"=>"B"],
["id"=>91,"difficulty"=>"medium","q"=>"Which is used for styling?","options"=>["A"=>"HTML","B"=>"CSS","C"=>"PHP","D"=>"SQL"],"answer"=>"B"],
["id"=>92,"difficulty"=>"medium","q"=>"Which is a browser engine?","options"=>["A"=>"Blink","B"=>"Python","C"=>"Node","D"=>"React"],"answer"=>"A"],
["id"=>93,"difficulty"=>"medium","q"=>"Which is a NoSQL DB?","options"=>["A"=>"MySQL","B"=>"MongoDB","C"=>"PostgreSQL","D"=>"Oracle"],"answer"=>"B"],
["id"=>94,"difficulty"=>"medium","q"=>"What is API used for?","options"=>["A"=>"Communication between systems","B"=>"Styling","C"=>"Storage","D"=>"Gaming"],"answer"=>"A"],
["id"=>95,"difficulty"=>"medium","q"=>"Which is a programming paradigm?","options"=>["A"=>"OOP","B"=>"HTML","C"=>"CSS","D"=>"HTTP"],"answer"=>"A"],
["id"=>96,"difficulty"=>"medium","q"=>"Which is used for authentication?","options"=>["A"=>"JWT","B"=>"HTML","C"=>"CSS","D"=>"PNG"],"answer"=>"A"],
["id"=>97,"difficulty"=>"medium","q"=>"What is compiler used for?","options"=>["A"=>"Translate code","B"=>"Store data","C"=>"Design UI","D"=>"Network"],"answer"=>"A"],
["id"=>98,"difficulty"=>"medium","q"=>"Which is a data structure?","options"=>["A"=>"Array","B"=>"HTML","C"=>"CSS","D"=>"HTTP"],"answer"=>"A"],
["id"=>99,"difficulty"=>"medium","q"=>"What is debugging?","options"=>["A"=>"Finding errors","B"=>"Writing code","C"=>"Deleting files","D"=>"Running OS"],"answer"=>"A"],
["id"=>100,"difficulty"=>"medium","q"=>"Which is client-side language?","options"=>["A"=>"JavaScript","B"=>"PHP","C"=>"Python","D"=>"SQL"],"answer"=>"A"],

/* ---------------- HARD (25) ---------------- */
["id"=>101,"difficulty"=>"hard","q"=>"What is time complexity of merge sort?","options"=>["A"=>"O(n)","B"=>"O(n log n)","C"=>"O(n^2)","D"=>"O(log n)"],"answer"=>"B"],
["id"=>102,"difficulty"=>"hard","q"=>"Which data structure uses FIFO?","options"=>["A"=>"Stack","B"=>"Queue","C"=>"Tree","D"=>"Graph"],"answer"=>"B"],
["id"=>103,"difficulty"=>"hard","q"=>"Which is not a design pattern?","options"=>["A"=>"Singleton","B"=>"Factory","C"=>"Observer","D"=>"Compiler"],"answer"=>"D"],
["id"=>104,"difficulty"=>"hard","q"=>"What is deadlock?","options"=>["A"=>"System crash","B"=>"Process waiting forever","C"=>"Memory leak","D"=>"CPU failure"],"answer"=>"B"],
["id"=>105,"difficulty"=>"hard","q"=>"Which algorithm is greedy?","options"=>["A"=>"Dijkstra","B"=>"Bubble sort","C"=>"DFS","D"=>"BFS"],"answer"=>"A"],
["id"=>106,"difficulty"=>"hard","q"=>"What is normalization?","options"=>["A"=>"Database optimization","B"=>"Encryption","C"=>"Compilation","D"=>"UI design"],"answer"=>"A"],
["id"=>107,"difficulty"=>"hard","q"=>"Which is a graph traversal?","options"=>["A"=>"DFS","B"=>"Stack","C"=>"Queue","D"=>"Array"],"answer"=>"A"],
["id"=>108,"difficulty"=>"hard","q"=>"What is polymorphism?","options"=>["A"=>"Multiple forms","B"=>"Single function","C"=>"Looping","D"=>"Memory allocation"],"answer"=>"A"],
["id"=>109,"difficulty"=>"hard","q"=>"Which is not OOP concept?","options"=>["A"=>"Inheritance","B"=>"Encapsulation","C"=>"Compilation","D"=>"Polymorphism"],"answer"=>"C"],
["id"=>110,"difficulty"=>"hard","q"=>"What is hashing used for?","options"=>["A"=>"Fast lookup","B"=>"UI design","C"=>"Networking","D"=>"Compilation"],"answer"=>"A"],
["id"=>111,"difficulty"=>"hard","q"=>"Which is stable sorting?","options"=>["A"=>"Merge sort","B"=>"Quick sort","C"=>"Selection sort","D"=>"Heap sort"],"answer"=>"A"],
["id"=>112,"difficulty"=>"hard","q"=>"What is recursion base case?","options"=>["A"=>"Stopping condition","B"=>"Loop start","C"=>"Error case","D"=>"Variable"],"answer"=>"A"],
["id"=>113,"difficulty"=>"hard","q"=>"Which structure is LIFO?","options"=>["A"=>"Queue","B"=>"Stack","C"=>"Graph","D"=>"Tree"],"answer"=>"B"],
["id"=>114,"difficulty"=>"hard","q"=>"Which is dynamic programming?","options"=>["A"=>"Memoization","B"=>"Sorting","C"=>"Searching","D"=>"Looping"],"answer"=>"A"],
["id"=>115,"difficulty"=>"hard","q"=>"What is abstraction?","options"=>["A"=>"Hiding complexity","B"=>"Writing code","C"=>"Looping","D"=>"Compilation"],"answer"=>"A"],
["id"=>116,"difficulty"=>"hard","q"=>"Which is not sorting algorithm?","options"=>["A"=>"Bubble","B"=>"Quick","C"=>"Binary search","D"=>"Merge"],"answer"=>"C"],
["id"=>117,"difficulty"=>"hard","q"=>"What is adjacency list used for?","options"=>["A"=>"Graphs","B"=>"Arrays","C"=>"Stacks","D"=>"Queues"],"answer"=>"A"],
["id"=>118,"difficulty"=>"hard","q"=>"Which is shortest path algorithm?","options"=>["A"=>"Dijkstra","B"=>"DFS","C"=>"Bubble sort","D"=>"Heap sort"],"answer"=>"A"],
["id"=>119,"difficulty"=>"hard","q"=>"What is memory leak?","options"=>["A"=>"Unused memory not freed","B"=>"CPU overload","C"=>"Disk failure","D"=>"Network error"],"answer"=>"A"],
["id"=>120,"difficulty"=>"hard","q"=>"Which is not part of OS?","options"=>["A"=>"Kernel","B"=>"Shell","C"=>"Compiler","D"=>"File system"],"answer"=>"C"],
["id"=>121,"difficulty"=>"hard","q"=>"What is thread?","options"=>["A"=>"Lightweight process","B"=>"File","C"=>"Variable","D"=>"Function"],"answer"=>"A"],
["id"=>122,"difficulty"=>"hard","q"=>"What is mutex used for?","options"=>["A"=>"Synchronization","B"=>"Sorting","C"=>"Memory storage","D"=>"Networking"],"answer"=>"A"],
["id"=>123,"difficulty"=>"hard","q"=>"Which is divide and conquer?","options"=>["A"=>"Merge sort","B"=>"Bubble sort","C"=>"Insertion sort","D"=>"Selection sort"],"answer"=>"A"],
["id"=>124,"difficulty"=>"hard","q"=>"What is compile time error?","options"=>["A"=>"Syntax error","B"=>"Runtime crash","C"=>"Logic error","D"=>"Memory error"],"answer"=>"A"],
["id"=>125,"difficulty"=>"hard","q"=>"Which is NP-complete problem?","options"=>["A"=>"Traveling Salesman","B"=>"Binary search","C"=>"Sorting","D"=>"Queue"],"answer"=>"A"]
];